language: node_js
node_js:
- lts/*
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
- export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
notifications:
  email: false
after_success:
- yarn cover
env:
  global:
    secure: GHBlAw4jkTWZE8iD16s4q0gYvC2URpitilFLw64Hmepr5sssxPHEW8k9QNGZFd04xY9a7LH2eohv+owiJlOunA3Uz0PCz8DZGwCjb/i/1jALcvED+WZl9pUIsYA5CFrPUvRsu3MODYnO2NJTwWNMdTfYXaFdZPxKLGxoqsqxhXfgCmm+QB469bcu+y3q1Fw+oGKC1Jj7lhMPLSOtYFWdQXUi8UCIMs32/dFuOaHFmcZs0DBYKffZQ5knS9h6HU9F0oqTxZRJk0yPuipteiZ1HuQjQKrsEkaugFKV4w9/PFnmmCBS+Xw0x/mdZ5PclagPHDHe/l8UKZDeFtTZEErnpAs65OrteDjw3v+QnCdG/aFuOcrC2jTHnPUl2zGT2aWlVZbCidHB5AFX+YNDBXUCYS+eaPJWx5PrPwHMFCcPsuni6PncgvoIIJnrtaj61GhikJ4aqgEDNzjFPmNduB/aZfxDoCCc2y0SXafHAxHfjhJPmN7hAYzLeXjSsx8gmmztpiPXUqAuJongIUPMs5Gmxl4jBQOIQ1YkOhEcsHTgYQIcQI6gjLuRhbPw0EBfbjPn1FRY3Xpr6zX4BKEn4EAJStA+lfLtfO0dxFxALRAzxVAOcaI3Uzgfg/qMTMPVJFST2hc1+RpAsihzSr5ubZ01teQ+qhUbsX5k7zPoKq0v2lU=
