language: node_js
node_js:
- lts/*
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
- export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
notifications:
  email: false
after_success:
- yarn cover
deploy:
  provider: heroku
  api_key:
    secure: 4c191615-b935-49d2-9fbc-5d3c6a120799
  app: epicmailapp
  on:
    all_branches: true
services:
  - postgresql
before_script:
  - psql -c 'create database epicmail_db;' -U postgres
