language: node_js
node_js:
  - "lts/*"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
notifications:
  email: false
before_script: chmod ugo+x scripts/create-data-dirs.sh
script: ./scripts/create-data-dirs.sh
env:
  - NODE_ENV="test"
  - PORT=3000
  - MORGAN="test"
  - ID_LENGTH=10
  - HASHING_SECRET="thisIsASecrete"