language: node_js
node_js:
- lts/*
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
- export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
notifications:
  email: false
after_success:
- yarn cover
deploy:
  provider: heroku
  api_key:
    secure: 4c191615-b935-49d2-9fbc-5d3c6a120799
  app: epicmailapp
  on:
    all_branches: true
env:
  global:
  - secure: "dSSf/B9PgKS42vQchsfTVEBL4zhSr0IbUXENLEakIt0yeto9h6tO1bMo/BA7CfhO4QOx08nYxb15dnKjk+3aBUzfETN9oIEjubZxrApoibqswiU9g5wCXX17KGqEF9scW7JcmkgMeWZ5oUiJTg46ZmYB6c6g/IhJ8dmcRytgitfKTMAPsaWboDB6Ef1CedzTonbkb65A4m6F4QFEj2tF203sh8osxthO0wQv1f4J9To+zdyHfSURQQaQy7x7AqyqKoNCdACoyq1Ksh3EZ61WzYsxsBHxvTJWFYqduzGFiG8YddPOEnEUNSAQLrLfO757ukO+ncm24ZlS3Y5XMgwRAzir1OwxmE79phT53J1USHXniwVLF9OfW9lBvL7j66x6X34+snI2iivovfjik6F9DtII/AmKn4h/a08hozpfFwZiTHUIimAobkOw8dwR/OKmKO5e4V+uS1gwAChKmrKr5sK+Rlf9XbKuWT0Awn9WJ/5k4ABk8HFSp1NkIndqTiurDYqLWUUfbRzRkOaP0wqkLfVAXMiLJsUWOzkeoTkhSir4hvUMDgwRumhVK09uKCr/9cjWS8hFnI0R2N8mHWsv9UYXrJFFUi8geKZN+bh9BMPlloipt9Y4/ZGVhKK9pZI5WA9QFdT/Jt4704oleaaQX1Y4DZit+WzPJ7aMB89KpPY="
  - PORT=3000
  - ID_LENGTH=10
  - HASHING_SECRET="thisIsASecret"
  - ADMIN_TOKEN="6zo2n5q7gjysiqp7o1k"
